EventsBrowser/EventsBrowser/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EventsBrowser.Models
{
    public class Artist
    {
        [Key]                            
        public int Id { get; set; }       
        [Display(Name ="Zdjęcie profilowe")]
        [Required(ErrorMessage = "Zdjęcie profilowe jest wymagane")]
        public string ProfilePictureUrl { get; set; }

        [Display(Name = "Nazwa")]
        [Required(ErrorMessage = "Nazwa jest wymagana")]
        [StringLength(50,MinimumLength =2, ErrorMessage = "Nazwa musi mieć co najmniej 2 znaki")]
        public string FullName { get; set; }

        [Display(Name = "Bio")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Bio musi zawierać minimum 5 znaków")]
        public string Bio { get; set; }

        public List<Artist_Event> Artists_Events { get; set; }
    }
}

EventsBrowser/EventsBrowser/Models/Artist_Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventsBrowser.Models
{
    public class Artist_Event
    {
        public int EventId { get; set; }

        public Event Event { get; set; }
        public int ArtistId { get; set; }
        public Artist Artist {get;set;}
    }
}

EventsBrowser/EventsBrowser/Models/ErrorViewModel.cs
using System;

namespace EventsBrowser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EventsBrowser/EventsBrowser/Models/Event.cs
using DocumentFormat.OpenXml.Drawing.Diagrams;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EventsBrowser.Data;
using System.ComponentModel.DataAnnotations.Schema;

namespace EventsBrowser.Models
{
    public class Event
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public double Price { get; set; }
        public string ImageUrl { get; set; }

        public DateTime Date { get; set; }

        public EventCategory Category { get; set; }

        //Relationships

        public List<Artist_Event>Artists_Events { get; set; }

        //EventPlace

        public int EventPlaceId { get; set; }
        [ForeignKey("EventPlaceId")]
        public EventPlace EventPlace { get; set; }
    }
}

EventsBrowser/EventsBrowser/Models/EventPlace.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EventsBrowser.Models
{
    public class EventPlace
    {
        [Key]
        public int Id { get; set; }
        [Display(Name="Zdjęcie obiektu")]
        public string Photo { get; set; }
        [Display(Name = "Miasto")]
        public string City { get; set; }
        [Display(Name = "Opis")]
        public string Description { get; set; }

        // Relationship
        public List <Event>Events { get; set; }
    }
}

EventsBrowser/EventsBrowser/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using EventsBrowser.Data.Services;
using EventsBrowser.Models;

namespace EventsBrowser.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly IArtistsService _service; // wysyłanie lub odbieranie danych z bazy
        public ArtistsController(IArtistsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        // GET/Artist/Create
        public  IActionResult  Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>Create([Bind("FullName,ProfilePictureUrl,Bio")]Artist artist)
        {
            if (!ModelState.IsValid)
            {
                return View(artist);

            }
            await _service.AddAsync(artist);
            return RedirectToAction(nameof(Index));
        }

        //GET/Artist/Details
        public async Task<IActionResult> Details (int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);
            if (artistDetails == null) return View("NotFound");
            return View(artistDetails);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,FullName,ProfilePictureUrl,Bio")] Artist artist)
        {
            if (!ModelState.IsValid)
            {
                return View(artist);

            }
            await _service.UpdateAsync(id,artist);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);
            if (artistDetails == null) return View("NotFound");
            return View(artistDetails);

        }
        //GET:Artist/Delete/id

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);
            if (artistDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
             
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var artistDetails = await _service.GetByIdAsync(id);
            if (artistDetails == null) return View("NotFound");
            return View(artistDetails);

        }
    }
}

EventsBrowser/EventsBrowser/Controllers/EventsController.cs
using EventsBrowser.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventsBrowser.Controllers
{
         
        public class EventsController : Controller
    {
        private readonly AppDbContext _context; 
        public EventsController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allEvents = await _context.Events.Include(m => m.EventPlace).ToListAsync();
            return View(allEvents);
        }
    }
}

EventsBrowser/EventsBrowser/Controllers/EventsPlacesController.cs
using EventsBrowser.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventsBrowser.Controllers
{
    public class EventsPlacesController : Controller
    {
        private readonly AppDbContext _context; // wysyłanie lub odbieranie danych z bazy
        public EventsPlacesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allEventsPlaces = await _context.EventPlaces.ToListAsync();
            return View(allEventsPlaces);
        }
    }
}

EventsBrowser/EventsBrowser/Views/Artists/Create.cshtml
@model Artist

@{
    ViewData["Title"] = "Dodaj artystę";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Dodaj nowego artystę</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureUrl" class="control-label"></label>
                        <input asp-for="ProfilePictureUrl" class="form-control" />
                        <span asp-validation-for="ProfilePictureUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Dodaj" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Wyświetl listę artystów</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script>
    // załaduje zdjęcie do podglądu z url

    $(document).ready(function () {
        var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureUrl").val();

    })

    $("#ProfilePictureUrl").on("change", function () {                  // dodawanie nowego zdjecia
        var output = document.getElementById('ProfilePictureUrlPreview'); //funkcja pobiera zdjecie z ProfilePicturePreview i wstawia w miejsce ProfilePictureUrl
        output.src = $(this).val();
    })
</script>
}

EventsBrowser/EventsBrowser/Views/Artists/Delete.cshtml
@model Artist

@{
    ViewData["Title"] = "Usuwanie artysty";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Usuwasz @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <div class="form-group text-center">
                    <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureUrl" class="control-label"></label>
                    <input asp-for="ProfilePictureUrl" class="form-control" />
                    <span asp-validation-for="ProfilePictureUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Usuń" class="btn btn-danger float-right" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

EventsBrowser/EventsBrowser/Views/Artists/Details.cshtml
@model Artist

@{
    ViewData["Title"] = "Szczegóły";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>@Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureUrl" class="control-label"></label>
                        <input asp-for="ProfilePictureUrl" class="form-control" />
                        <span asp-validation-for="ProfilePictureUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                         
                        <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Wyświetl listę artystów</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
    // załaduje zdjęcie do podglądu z url

    $(document).ready(function () {
        var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureUrl").val();

    })

    </script>
}

EventsBrowser/EventsBrowser/Views/Artists/Edit.cshtml
@model Artist

@{
    ViewData["Title"] = "Aktualizacja danych artysty";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Aktualizuj dane artysty</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureUrl" class="control-label"></label>
                        <input asp-for="ProfilePictureUrl" class="form-control" />
                        <span asp-validation-for="ProfilePictureUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Wyświetl listę artystów</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script>
    // załaduje zdjęcie do podglądu z url

    $(document).ready(function () {
        var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureUrl").val();

    })

    $("#ProfilePictureUrl").on("change", function () {                  // dodawanie nowego zdjecia
        var output = document.getElementById('ProfilePictureUrlPreview'); //funkcja pobiera zdjecie z ProfilePicturePreview i wstawia w miejsce ProfilePictureUrl
        output.src = $(this).val();
    })
</script>
}

EventsBrowser/EventsBrowser/Views/Artists/Index.cshtml
@model IEnumerable<Artist>
 
@{
    ViewData["Title"] = "List of Artists";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureUrl)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
@foreach (var item in Model)
            {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ProfilePictureUrl" alt="@item.FullName" style="max-width:150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem=>item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    <td class="align-middle">
                        <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                        <a class="btn btn-outline-info"  asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>

    </div>
</div>

<div style="position: fixed; right:25px; bottom:70px;" class="text-white">
    <a asp-controller="Artists" asp-action="Create" class="btn btn-success"> <i class="bi bi-plus-circle"></i>Dodaj nowedo artyste</a>
</div>

EventsBrowser/EventsBrowser/Views/Events/Index.cshtml
@model IEnumerable<Event>

@{
    ViewData["Title"] = "Wydarzenia";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                   
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6 ">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Miejsce: </b>@item.EventPlace.City</p>
                            <p class="card-text"><b>Rodzaj wydarzenia: </b>@item.Category</p>
                            <p class="card-text"><b>Data: </b>@item.Date.ToString("dd MMM yy")</p>
                            
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.Date && DateTime.Now <= item.Date)
                                {
                                    <span class="badge bg-success text-white">Dostępne</span>
                                }
                                else if (DateTime.Now > item.Date)
                                {
                                    <span class="badge bg-danger text-white">Wygasło</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">Nadchodzące</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Szczegóły
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.Date) ? "disabled" : "")"
                                   asp-controller="Orders"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Dodaj do koszyka (Cena @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

EventsBrowser/EventsBrowser/Views/EventsPlaces/Index.cshtml
@model IEnumerable<EventPlace>

@{
    ViewData["Title"] = "Obiekty";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Photo)</th>
                    <th>@Html.DisplayNameFor(model => model.City)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Photo" alt="@item.City" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

EventsBrowser/EventsBrowser/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Koniec internetów</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Events" asp-action="Index">Strona Główna</a>
    </div>
</div>

EventsBrowser/EventsBrowser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventsBrowser</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Events" asp-action="Index">EventsBrowser</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index"><i class="bi bi-film"></i>Wydarzenia</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Zarządzaj
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="EventsPlaces" asp-action="Index"><i class="bi bi-camera-reels"></i>Obiekty</a>
                                <a class="dropdown-item" asp-controller="Events" asp-action="Index"><i class="bi bi-headset"></i>Wydarzenia</a>
                                <a class="dropdown-item" asp-controller="Artists" asp-action="Index"><i class="bi bi-person-square"></i>Artyści</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Events" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Podaj nazwe wydarzenia..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EventsBrowser 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>